version: "3"
services:
  ss-server:
    container_name: ss-server
    image: mritd/shadowsocks
    ports:
      - "6500:6500"
    envrionment:
      - SS_MODULE=ss-server
      - SS_CONFIG="-s 0.0.0.0 -p 6500 -m aes-256-cfb -k abc123_ --fast-open"

  ss-client:
    container_name: ss-client
    image: mritd/shadowsocks
    ports:
      - "1080:1080"
    envrionment:
      - SS_MODULE=ss-client
      - SS_CONFIG="-s server_ip -p 6500 -b 0.0.0.0 -l 1080 -m aes-256-cfb -k abc123_ --fast-open"
